### ISSUE TITLE
How do I run an .HX file?

### ISSUE THREAD

**Issue by GH6** [heriet/hxPixel#3]
I'd like to run GalDecoder.HX. But I'm not sure how to run the HX file and how to compiler it.
Can you tell me how to do it?

**Comment by heriet** [comment]
GalDecoder.hx is libraly for Haxe.

see 
- Haxe documantation https://haxe.org/manual/introduction-hello-world.html
- hxPixel sample https://github.com/heriet/hxPixel/tree/master/samples/neko
    - you can open .hxproj files by Flash Develop http://www.flashdevelop.org/
- gizac (it is tool using GalDecoder) https://github.com/heriet/gizac
